# Generated by Django 3.2.7 on 2024-11-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_turf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='turf',
            name='available_services',
        ),
        migrations.AddField(
            model_name='turf',
            name='available_services',
            field=models.ManyToManyField(blank=True, to='home.Service'),
        ),
    ]
