# Generated by Django 3.2.7 on 2024-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20241107_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='turf',
            name='available_services',
            field=models.ManyToManyField(related_name='turfs', to='home.Service'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='image',
            field=models.ImageField(upload_to='turfs/'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='turf',
            name='timing_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='timing_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turf',
            name='turf_type',
            field=models.CharField(max_length=255),
        ),
    ]
