# Generated by Django 3.2.7 on 2024-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20241107_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='available_services',
            field=models.ManyToManyField(blank=True, to='home.Service'),
        ),
    ]
