# Generated by Django 3.2.7 on 2024-11-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
