# Generated by Django 3.2.7 on 2024-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='booked', max_length=20),
        ),
    ]
